---
apiVersion: authorization.openshift.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.serviceaccount }}-role-view-default
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceaccount }}
roleRef:
  name: view